---
title: "Model development"
output: html_notebook
---

```{r setup}
library(rstan)
library(cmdstanr)
library(tidyverse)
library(cowplot)
theme_set(theme_cowplot())

options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

source("R/evaluation_tools.R")
source("R/sbc.R")
source("R/sampling_multi.R")
source("R/hmm_kalman_devel_tools.R")

```


```{r}
#system.time({
model <- cmdstan_model(stan_file = here::here("hmm_kalman.stan"))
#})
#system.time({
#model <- rstan::stan_model(file = here::here("hmm_kalman.stan"))
#})
```


```{r}
inv_gamma_match_error <- function(p, q025, q975) {
  alpha <- p[1]
  beta <- p[2]
  inv_gamma_cdf <- function(x, alpha, beta) { pgamma(beta / x, alpha, lower = FALSE) }
  (inv_gamma_cdf(q025, alpha, beta) - 0.025)^2 + (inv_gamma_cdf(q975, alpha, beta) - 0.975)^2
}

opt_res <- nlm(inv_gamma_match_error, p = c(1,1), q025 = 0.5, q975 = 10)
sims <- 1/rgamma(1e5,shape = opt_res$estimate[1], rate = opt_res$estimate[2])
mean(sims < 0.5)
mean(sims > 10)
hist(sims)
```



Single test

```{r}
adapt_delta <- 0.8
data <- simulator(N_patients = 5, N_patients_unknown_load = 0, N_time = 10, N_treatments = 0, N_obs_per_patient = 4, prior = prior)
if(inherits(model, "stanmodel")) {
  fit <- sampling(model, data = data$observed, control = list(adapt_delta = adapt_delta))
} else {
  cmdstan_fit <- model$sample(data = data$observed, adapt_delta = adapt_delta)
  fit <- rstan::read_stan_csv(cmdstan_fit$output_files())
}
evaluation_summary(fit, data$true)

# plot_sim_data_true(data)
plot_sim_data_observed(data)

data$true


```

```{r}
for(i in 1:10) {
  data <- simulator(N_patients = 5, N_patients_unknown_load = 0, N_time = 10, N_treatments = 0, N_obs_per_patient = 4, prior = prior)
  
  (plot_sim_data_observed(data) + ggtitle("Observed",i)) %>% print()
  (plot_sim_data_true(data) + ggtitle("true",i)) %>% print()
  cat("\n======== ",i, " ===========\n")
  print(data$true)
}
```


SBC

```{r}
sbc_res <- sbc(model, generator = function() {simulator(N_patients = 30, N_patients_unknown_load = 5, N_time = 15, N_obs_per_patient = 4, N_treatments = 1, prior = prior, time_effect = FALSE)}, N_steps = 500, control = list(adapt_delta = adapt_delta))

sbc_res$params %>% plot_sbc_params(binwidth = 5)
summarise_sbc_diagnostics(sbc_res)
sbc_res$diagnostics
```


```{r}
id <- 14
data <- list(observed = sbc_res$data[[id]], true = sbc_res$true_values[[id]])
if(inherits(model, "stanmodel")) {
  fit <- sampling(model, data = data$observed, control = list(adapt_delta = adapt_delta))
} else {
  cmdstan_fit <- model$sample(data = data$observed, adapt_delta = adapt_delta)
  fit <- rstan::read_stan_csv(cmdstan_fit$output_files())
}
evaluation_summary(fit, sbc_res$true_values[[id]])
data$true

plot_sim_data_observed(data) %>% print()

launch_shinystan_nonblocking(fit)


#sbc_res$true_values[[i]]
```

```{r}
plot_sim_data_observed(data)

```


```{r}
#bayesplot::mcmc_parcoord(fit, regex_pars = c("initial_disease_raw"), np = bayesplot::nuts_params(fit))
#bayesplot::mcmc_parcoord(fit, regex_pars = c("baseline_slopes_raw"), np = bayesplot::nuts_params(fit))

bayesplot::mcmc_parcoord(fit, pars = c("sigma","baseline_slopes_mean","baseline_slopes_sd"), np = bayesplot::nuts_params(fit))

bayesplot::mcmc_parcoord(fit, pars = c("sigma","baseline_slopes_mean","baseline_slopes_sd","t_high"), np = bayesplot::nuts_params(fit))
```
